language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - echo "Everything good !"

